export const PROFILE_FEED_CONNECT = 'PROFILEFEED_ORDERS_CONNECT';
export const PROFILE_FEED_CONNECTING = 'PROFILEFEED_ORDERS_WS_CONNECTING';
export const PROFILE_FEED_ERROR = 'PROFILEFEED_ORDERS_WS_ERROR';
export const PROFILE_FEED_OPEN = 'PROFILEFEED_ORDERS_WS_OPEN';
export const PROFILE_FEED_CLOSE = 'PROFILEFEED_ORDERS_WS_CLOSE';
export const PROFILE_FEED_GET_FEED = 'PROFILEFEED_ORDERS_WS_MESSAGE';
export const PROFILE_FEED_DISCONNECT = 'PROFILEFEED_ORDERS_DISCONNECT';

export const connect = (url) => ({
    type: PROFILE_FEED_CONNECT,
    payload: url
});

export const disconnect = () => ({
    type: PROFILE_FEED_DISCONNECT
});